#!/bin/bash
echo "You passed the following list : $morphing_positions"
#we assume morphed airfoils have all the basename Def_n.csv where n is in our case the vertical deformation of a reference point in the morphing LE
cd $AIRFOIL_FILES

echo Importing airfoil files of $morphing_positions positions
echo ""

for i in $morphing_positions; do 
	cp $FOIL_BASENAME${i}.csv $GMSH_BIN_DIR
done

ls

echo Copying the .geo generator template
echo "#####################"

cd $TOOLS_DIR
cp dotgeogenerator.py $GMSH_BIN_DIR
cd $GMSH_BIN_DIR

# PENDIENTE LEER EL VALOR DE LA Y+, SUSTITUIRLO SI LO DESEO CON EL CÓDIGO DEL YPLUS echo Do you want to change the first layer cell height?

echo "Generating .py files"
for i in $morphing_positions;do
	cp dotgeogenerator.py $FOIL_BASENAME${i}.py	
	sed -i -e "s/airfoil_file.csv/$FOIL_BASENAME${i}.csv/g" \
	-e "s/airfoil_file.dat/$FOIL_BASENAME${i}.dat/g" \
	-e "s/airfoil_mesh.geo/$FOIL_BASENAME${i}.geo/g" \
	-e "s/airfoil_mesh.msh/$FOIL_BASENAME${i}.msh/g" $FOIL_BASENAME${i}.py
done

echo Done, directory looks like this now
echo "#####################"
ls
echo "#####################"

echo Executing .py files to obtain .geo
for i in $morphing_positions;do
	python $FOIL_BASENAME${i}.py
done

cd $GMSH_BIN_DIR
for i in $morphing_positions;do
	./gmsh $FOIL_BASENAME${i}.geo &
	sleep 5
	pkill gmsh
done
mv $FOIL_BASENAME*.msh $CURRENT_PROJECT
cd $CURRENT_PROJECT

for i in $morphing_positions;do
	mv $FOIL_BASENAME${i}.msh $i/caso_gen/
	cd $i/caso_gen/
	gmshToFoam $FOIL_BASENAME${i}.msh > "log.gmshToFoam_$FOIL_BASENAME${i}"
#	cp boundary_corrected constant/polyMesh/boundary THIS LINE CREATES CONFLICT IF YOU CHANGE THE MESH SETUP (e.g y+) bc of faces labeling
	cd constant/polyMesh/
	#WARNING: THESE LINES ARE EXTREMELY CASE SPECIFIC. YOU NEED TO CHECK THE BOUNDARY FILE AND MODIFY THE SED CMDs
	sed -i '/physicalType    patch/d' boundary #physicaltype lines
	sed -i '/type            patch;/d' boundary
	sed -i '21 a ,        type            empty;' boundary
	sed -i '27 a ,        type            empty;' boundary
	sed -i '33 a ,        type            wall;' boundary
	sed -i '39 a ,        type            patch;' boundary
	sed -i 's/,//g' boundary
	cd ../../	
	checkMesh > "log.checkMesh_$FOIL_BASENAME${i}"
#	renumberMesh -overwrite > "log.renumberMesh_$FOIL_BASENAME${i}" It spoiled the $internalField substitution in 0/. This command is run in run_anglerange
	rm $FOIL_BASENAME${i}.msh
	cd ../../
done