#!/bin/bash
cd $GMSH_BIN_DIR
for i in $morphing_positions;do
	./gmsh $FOIL_BASENAME${i}.geo &
	sleep 5
	pkill gmsh
done
mv $FOIL_BASENAME*.msh $CURRENT_PROJECT
cd $CURRENT_PROJECT

for i in $morphing_positions;do
	mv $FOIL_BASENAME${i}.msh $i/caso_gen/
	cd $i/caso_gen/
	gmshToFoam $FOIL_BASENAME${i}.msh > "log.gmshToFoam_$FOIL_BASENAME${i}"
#	cp boundary_corrected constant/polyMesh/boundary THIS LINE CREATES CONFLICT IF YOU CHANGE THE MESH SETUP (e.g y+) bc of faces labeling
	cd constant/polyMesh/
	#WARNING: THESE LINES ARE EXTREMELY CASE SPECIFIC. YOU NEED TO CHECK THE BOUNDARY FILE AND MODIFY THE SED CMDs
	sed -i '/physicalType    patch/d' boundary #physicaltype lines
	sed -i '/type            patch;/d' boundary
	sed -i '21 a ,        type            empty;' boundary
	sed -i '27 a ,        type            empty;' boundary
	sed -i '33 a ,        type            wall;' boundary
	sed -i '39 a ,        type            patch;' boundary
	sed -i 's/,//g' boundary
	cd ../../	
	checkMesh > "log.checkMesh_$FOIL_BASENAME${i}"
#	renumberMesh -overwrite > "log.renumberMesh_$FOIL_BASENAME${i}" It spoiled the $internalField substitution in 0/. This command is run in run_anglerange
	rm $FOIL_BASENAME${i}.msh
	cd ../../
done