#!/bin/bash
echo "You passed the following list : $morphing_positions"
#we assume morphed airfoils have all the basename Def_n.csv where n is in our case the vertical deformation of a reference point in the morphing LE

export FOIL_BASENAME=Def_
cd $AIRFOIL_FILES

echo Importing airfoil files of $morphing_positions positions
echo ""

for i in $morphing_positions; do 
	cp $FOIL_BASENAME${i}.csv $GMSH_BIN_DIR
done

ls

echo Copying the .geo generator template
echo "#####################"

cd $TOOLS_DIR
cp dotgeogenerator.py $GMSH_BIN_DIR
cd $GMSH_BIN_DIR

# PENDIENTE LEER EL VALOR DE LA Y+, SUSTITUIRLO SI LO DESEO CON EL CÓDIGO DEL YPLUS echo Do you want to change the first layer cell height?

echo "Generating .py files"
for i in $morphing_positions;do
	cp dotgeogenerator.py $FOIL_BASENAME${i}.py	
	sed -i -e "s/airfoil_file.csv/$FOIL_BASENAME${i}.csv/g" \
	-e "s/airfoil_file.dat/$FOIL_BASENAME${i}.dat/g" \
	-e "s/airfoil_mesh.geo/$FOIL_BASENAME${i}.geo/g" \
	-e "s/airfoil_mesh.msh/$FOIL_BASENAME${i}.msh/g" $FOIL_BASENAME${i}.py
done

echo Done, directory looks like this now
echo "#####################"
ls
echo "#####################"

echo Executing .py files to obtain .geo
for i in $morphing_positions;do
	python $FOIL_BASENAME${i}.py
done

cd $AIRFOILAPPDIR
