#!/bin/bash
source /opt/OpenFOAM-7/etc/bashrc
cd $CURRENT_PROJECT
for i in $morphing_positions;do
	cd $i
	CURRENT_DEF=$i
	echo "slept for 10"
	sleep 10
	python Preparador_casos.py
	echo "slept for 10"
	sleep 10
	./run_anglerange
	cd ..
done

