#!/bin/bash
cp $TOOLS_DIR/Preparador_casos.py $CURRENT_PROJECT
cp $TOOLS_DIR/run_anglerange $CURRENT_PROJECT
cd $CURRENT_PROJECT

sed -i "s/userdefrange/$anglerange/" Preparador_casos.py

sed -i "s/user_defined_range/$bashrange/" run_anglerange

parallel cp run_anglerange Preparador_casos.py ::: $morphing_positions

cd $AIRFOILAPPDIR
