#!/bin/sh
rm -r *[1-9]*
echo Los AoA simulados son los siguientes:
ls resultados/paraview/
echo Elige el AoA que quieres visualizar:
read AoA
cp -r resultados/paraview/$AoA/*[1-9]* ./
simpleFoam -postProcess -func yPlus
simpleFoamResidual
paraFoam -builtin 
#quedaría extenderlo a varios AoA a la vez y tener la opción de elegir uno o más

